/** Generates the in-game "Credits & Licenses" data (src/data/credits.ts) and the matching block in
 * THIRD_PARTY_NOTICES.md from package.json/package-lock.json and assets/audio/imports.json.
 * Run `npx tsx tools/credits/generate.ts` after changing production dependencies or audio sources. */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import imports from '../../assets/audio/imports.json';

export interface Credit { title: string; author: string; url: string; license: string; licenseUrl: string; authorUrl?: string; detail?: string; files?: string[] }
const spdx = (id: string) => `https://spdx.org/licenses/${id}.html`;
const CC0 = 'https://creativecommons.org/publicdomain/zero/1.0/';

/** Authored third-party content outside npm and the audio ledger (keep in sync with THIRD_PARTY_NOTICES.md prose). */
const technology: Credit[] = [
    { title: 'folio-2025 (source patterns adapted at commit 41046b5)', author: 'Bruno Simon', url: 'https://github.com/brunosimon/folio-2025', license: 'MIT', licenseUrl: spdx('MIT'), detail: 'Engine, input, UI, rendering, vehicle and audio patterns; no art, meshes, textures or audio reused.' },
    { title: 'Mesh2Motion human rig and animation clips', author: 'Mesh2Motion (Scott Petrovic and contributors)', url: 'https://github.com/Mesh2Motion/mesh2motion-app', license: 'CC0 1.0', licenseUrl: CC0, detail: 'Rig and animations retargeted to our original characters (pinned commit 79f3f61).' },
    { title: 'meshoptimizer decoder (bundled with three.js addons)', author: 'Arseny Kapoulkine', url: 'https://github.com/zeux/meshoptimizer', license: 'MIT', licenseUrl: spdx('MIT') },
    { title: 'Basis Universal transcoder (public/assets/basis)', author: 'Binomial LLC', url: 'https://github.com/BinomialLLC/basis_universal', license: 'Apache-2.0', licenseUrl: spdx('Apache-2.0') },
];
const original: Credit = { title: 'Game code, 3D models, textures, UI art and synthesized cues', author: 'Minor Incident contributors', url: '', license: 'MIT', licenseUrl: spdx('MIT'), detail: 'Original work; synthesized system cues come from src/audio/synthesis.ts.' };
const authorUrls: Record<string, string> = { 'Zander Noriega': 'https://soundcloud.com/zander-noriega' };

type Source = (typeof imports.sources)[keyof typeof imports.sources];
const source = (id: string) => (imports.sources as Record<string, Source>)[id];

export function codeCredits(): Credit[] {
    const pkg = JSON.parse(readFileSync('package.json', 'utf8')) as { dependencies: Record<string, string> };
    const lock = JSON.parse(readFileSync('package-lock.json', 'utf8')) as { packages: Record<string, { version: string; license?: string }> };
    const deps = Object.keys(pkg.dependencies).sort().map(name => {
        const entry = lock.packages[`node_modules/${name}`];
        if (!entry?.license) throw new Error(`No locked license for production dependency ${name}`);
        return { title: `${name} ${entry.version}`, author: name, url: `https://www.npmjs.com/package/${name}`, license: entry.license, licenseUrl: spdx(entry.license) };
    });
    return [...deps, ...technology];
}

/** One entry per source pack (page + author + license), listing every member file a shipped cue or stream uses. */
export function audioCredits(): Credit[] {
    const used = [...Object.values(imports.streams).map(s => s.source), ...Object.values(imports.cues).map(c => c.source)];
    const packs = new Map<string, Credit & { titles: Set<string>; files: string[] }>();
    for (const id of new Set(used)) {
        const s = source(id);
        const key = `${s.url}|${s.author}|${s.license}`;
        let pack = packs.get(key);
        if (!pack) {
            pack = { title: '', author: s.author, url: s.url, license: s.license, licenseUrl: s.licenseUrl, titles: new Set(), files: [], ...(authorUrls[s.author] ? { authorUrl: authorUrls[s.author] } : {}) };
            packs.set(key, pack);
        }
        pack.titles.add(s.title.split(': ')[0]);
        const file = s.member.split('/').at(-1)!;
        if (!pack.files.includes(file)) pack.files.push(file);
    }
    return [...packs.values()].map(({ titles, files, ...credit }) => ({ ...credit, title: [...titles].join('; '), files: files.sort((a, b) => a.localeCompare(b, 'en', { numeric: true })) }));
}

export function render(): { ts: string; notices: string } {
    const code = codeCredits(), audio = audioCredits();
    const ts = ['// Generated by tools/credits/generate.ts from package.json, package-lock.json and assets/audio/imports.json. Do not edit.',
        '/** Shape of every in-game credit row. */',
        'export interface Credit { title: string; author: string; url: string; license: string; licenseUrl: string; authorUrl?: string; detail?: string; files?: readonly string[] }',
        `export const codeCredits: readonly Credit[] = ${JSON.stringify(code, null, 4)};`,
        `export const audioCredits: readonly Credit[] = ${JSON.stringify(audio, null, 4)};`,
        `export const originalCredit: Credit = ${JSON.stringify(original, null, 4)};`, ''].join('\n');
    const line = (c: Credit) => `- ${c.title} — ${c.author}${c.authorUrl ? ` (${c.authorUrl})` : ''}.${c.url ? ` Source: ${c.url}.` : ''} License: ${c.license} (${c.licenseUrl}).${c.detail ? ` ${c.detail}` : ''}${c.files ? ` Files: ${c.files.join(', ')}.` : ''}`;
    const notices = ['<!-- credits:start (generated by tools/credits/generate.ts; shown in-game under Credits & Licenses) -->',
        '## Runtime libraries and technology', '', ...code.map(line), '',
        '## Recorded music and sound credits', '',
        'Every recording below was modified for the game: excerpts, EQ, pitch, fades, compression, loudness normalization and Opus/AAC encoding.', '',
        ...audio.map(line), '', '## Original work', '', line(original), '<!-- credits:end -->'].join('\n');
    return { ts, notices };
}

export function noticesWith(current: string, block: string): string {
    const start = current.indexOf('<!-- credits:start'), end = current.indexOf('<!-- credits:end -->');
    if (start < 0 || end < 0) throw new Error('THIRD_PARTY_NOTICES.md lacks the credits markers');
    return current.slice(0, start) + block + current.slice(end + '<!-- credits:end -->'.length);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const { ts, notices } = render();
    writeFileSync('src/data/credits.ts', ts);
    writeFileSync('THIRD_PARTY_NOTICES.md', noticesWith(readFileSync('THIRD_PARTY_NOTICES.md', 'utf8'), notices));
}
