import { expect, test } from './fixtures';
import { hudStart, menuUrl } from './ui-helpers';
import { missionSandbox } from '../fixtures/scenarios/mission-sandbox';
import { vehicleDef } from '../../src/data/vehicles';
import { onboardingKey } from '../../src/ui/Onboarding';
test.use({ hasTouch: true });
test('T-E14-04 @E14 @E14-AC04 active mouse/keyboard/touch glyphs, including rebind; once per action per save', async ({ page }) => {
  await page.addInitScript(key => { if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(['move', 'evade', 'interact', 'pickup'])); }, onboardingKey);
  await hudStart(page);
  const def = missionSandbox('custom'); def.id = 'L1';
  await page.evaluate(async def => { const api = window.__SS__!; api.missions.load(def); api.missions.begin(); await api.step(1); }, def);
  const prompt = page.getByTestId('onboarding-prompt');
  await expect(prompt).toHaveAttribute('data-action', 'attack'); await expect(prompt).toContainText('☝ Action');
  await page.mouse.move(800, 450); await page.evaluate(() => window.__SS__!.step(1)); await expect(prompt).toContainText('LMB');
  await page.keyboard.press('ArrowUp'); await page.evaluate(() => window.__SS__!.step(1)); await expect(prompt).toContainText('J');
  await page.evaluate(() => window.__SS__!.input.rebind('left', 'KeyF'));
  await page.evaluate(() => window.__SS__!.step(1)); await expect(prompt).toContainText('F');
  await page.touchscreen.tap(60, 600); await page.evaluate(() => window.__SS__!.step(1)); await expect(prompt).toContainText('☝ Action');
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), onboardingKey); expect(saved).toContain('attack');
  await page.reload(); await page.waitForFunction(() => Boolean(window.__SS__)); await page.evaluate(() => window.__SS__!.ready);
  await page.evaluate(async def => { const api = window.__SS__!; await api.loadScenario('mission-sandbox'); api.pause(); api.missions.load(def); api.missions.begin(); await api.step(1); }, def);
  await expect(prompt).toBeHidden();
});
test('@E14 @E14-AC04 onboarding presents L2 selector and second side; L3 vehicle only when present', async ({ page }) => {
  await hudStart(page);
  const def = missionSandbox('custom'); def.id = 'L2';
  await page.evaluate(async def => { const api = window.__SS__!; api.missions.load(def); api.missions.begin(); await api.step(1); }, def);
  await expect(page.getByTestId('onboarding-prompt')).toHaveAttribute('data-action', 'selector');
  await page.keyboard.press('KeyQ'); await page.evaluate(() => window.__SS__!.step(16));
  await expect(page.getByTestId('onboarding-prompt')).toHaveAttribute('data-action', 'second-side');
  await page.keyboard.press('KeyK'); await page.evaluate(() => window.__SS__!.step(1));
  await expect(page.getByTestId('onboarding-prompt')).toBeHidden();
  await page.goto(menuUrl); await page.waitForFunction(() => Boolean(window.__SS__)); await page.evaluate(() => window.__SS__!.ready);
  await page.evaluate(async def => { const api = window.__SS__!; await api.loadScenario('mission-sandbox'); api.pause(); def.id = 'L3'; api.missions.load(def); api.missions.begin(); await api.step(1); }, def);
  await expect(page.getByTestId('onboarding-prompt')).toBeHidden();
  const car = await page.evaluate(async () => { const api = window.__SS__!; const id = api.spawn('vehicle.sedan', { x: 10, z: 10 }); await api.step(120); return id; });
  await expect(page.getByTestId('onboarding-prompt')).toHaveAttribute('data-action', 'vehicle');
  await page.evaluate(async ({ car, width }) => { const api = window.__SS__!, p = api.getEntity(car)!.transform; api.teleport('player', { x: p.x + .2, z: p.z + width / 2 + .55 }); api.input.clear(); await api.step(40); }, { car, width: vehicleDef('vehicle.sedan').width });
  await expect(page.getByTestId('onboarding-prompt')).toBeHidden();
});

test('@E14 @E14-AC04 L1 move → evade → interact → weapon pickup → attack uses real sim events', async ({ page }) => {
  await hudStart(page);
  const def = missionSandbox('custom'); def.id = 'L1';
  await page.evaluate(async def => { const api = window.__SS__!; api.missions.load(def); api.missions.begin(); await api.step(1); }, def);
  const prompt = page.getByTestId('onboarding-prompt');
  await expect(prompt).toHaveAttribute('data-action', 'move');
  await page.keyboard.down('KeyW'); await page.evaluate(() => window.__SS__!.step(30));
  await expect(prompt).toHaveAttribute('data-action', 'evade');
  await page.evaluate(() => window.__SS__!.step(90)); await page.keyboard.up('KeyW');
  await page.evaluate(async () => { const api = window.__SS__!, p = api.getState().player!.transform; api.spawn('device.radio', { x: p.x, z: p.z }, { holdTime: .6 }); api.input.clear(); await api.step(1); });
  await expect(prompt).toHaveAttribute('data-action', 'interact');
  await page.evaluate(() => window.__SS__!.step(36));
  await page.evaluate(async () => { const api = window.__SS__!, p = api.getState().player!.transform; api.spawn('weapon.bat', { x: p.x + 2, z: p.z }); await api.step(1); });
  await expect(prompt).toHaveAttribute('data-action', 'pickup');
  await page.evaluate(async () => { const api = window.__SS__!, p = api.getState().player!.transform; api.teleport('player', { x: p.x + 2, z: p.z }); await api.step(1); });
  await expect(prompt).toHaveAttribute('data-action', 'attack');
  await page.getByTestId('touch-left').tap(); await page.evaluate(() => window.__SS__!.step(1));
  await expect(prompt).toBeHidden();
});
