// Generated by tools/credits/generate.ts from package.json, package-lock.json and assets/audio/imports.json. Do not edit.
/** Shape of every in-game credit row. */
export interface Credit { title: string; author: string; url: string; license: string; licenseUrl: string; authorUrl?: string; detail?: string; files?: readonly string[] }
export const codeCredits: readonly Credit[] = [
    {
        "title": "@dimforge/rapier3d-compat 0.21.0",
        "author": "@dimforge/rapier3d-compat",
        "url": "https://www.npmjs.com/package/@dimforge/rapier3d-compat",
        "license": "Apache-2.0",
        "licenseUrl": "https://spdx.org/licenses/Apache-2.0.html"
    },
    {
        "title": "three 0.186.0",
        "author": "three",
        "url": "https://www.npmjs.com/package/three",
        "license": "MIT",
        "licenseUrl": "https://spdx.org/licenses/MIT.html"
    },
    {
        "title": "tweakpane 4.0.5",
        "author": "tweakpane",
        "url": "https://www.npmjs.com/package/tweakpane",
        "license": "MIT",
        "licenseUrl": "https://spdx.org/licenses/MIT.html"
    },
    {
        "title": "folio-2025 (source patterns adapted at commit 41046b5)",
        "author": "Bruno Simon",
        "url": "https://github.com/brunosimon/folio-2025",
        "license": "MIT",
        "licenseUrl": "https://spdx.org/licenses/MIT.html",
        "detail": "Engine, input, UI, rendering, vehicle, explosion (impulse, fireball, roll kick, bullet time) and audio patterns; no art, meshes, textures or audio reused."
    },
    {
        "title": "Mesh2Motion human rig and animation clips",
        "author": "Mesh2Motion (Scott Petrovic and contributors)",
        "url": "https://github.com/Mesh2Motion/mesh2motion-app",
        "license": "CC0 1.0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "detail": "Rig and animations retargeted to our original characters (pinned commit 79f3f61)."
    },
    {
        "title": "meshoptimizer decoder (bundled with three.js addons)",
        "author": "Arseny Kapoulkine",
        "url": "https://github.com/zeux/meshoptimizer",
        "license": "MIT",
        "licenseUrl": "https://spdx.org/licenses/MIT.html"
    },
    {
        "title": "Basis Universal transcoder (public/assets/basis)",
        "author": "Binomial LLC",
        "url": "https://github.com/BinomialLLC/basis_universal",
        "license": "Apache-2.0",
        "licenseUrl": "https://spdx.org/licenses/Apache-2.0.html"
    }
];
export const audioCredits: readonly Credit[] = [
    {
        "title": "Running free; comfort in uncertainty",
        "author": "bbatv / bbatv1",
        "url": "https://opengameart.org/content/peace-is-king-here",
        "license": "CC-BY 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
        "files": [
            "01 Running free_0.mp3",
            "09 __comfort in uncertainty 1.mp3"
        ]
    },
    {
        "title": "Blinding Lights",
        "author": "Zander Noriega",
        "url": "https://opengameart.org/content/blinding-lights",
        "license": "CC-BY 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
        "authorUrl": "https://soundcloud.com/zander-noriega",
        "files": [
            "Zander Noriega - Blinding Lights.wav"
        ]
    },
    {
        "title": "Jazz Brunch",
        "author": "Kevin MacLeod (incompetech.com)",
        "url": "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1700074",
        "license": "CC-BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
        "files": [
            "Jazz Brunch.mp3"
        ]
    },
    {
        "title": "Zombies sound pack",
        "author": "artisticdude",
        "url": "https://opengameart.org/content/zombies-sound-pack",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "zombie-1.wav",
            "zombie-2.wav",
            "zombie-3.wav",
            "zombie-4.wav",
            "zombie-5.wav",
            "zombie-6.wav",
            "zombie-7.wav",
            "zombie-8.wav",
            "zombie-9.wav",
            "zombie-10.wav",
            "zombie-11.wav",
            "zombie-12.wav",
            "zombie-13.wav",
            "zombie-14.wav",
            "zombie-15.wav",
            "zombie-16.wav",
            "zombie-17.wav",
            "zombie-18.wav",
            "zombie-19.wav",
            "zombie-20.wav",
            "zombie-21.wav",
            "zombie-22.wav",
            "zombie-23.wav"
        ]
    },
    {
        "title": "Zombie Sound Effects",
        "author": "Bendzer",
        "url": "https://opengameart.org/content/zombie-sound-effects-by-bendzer",
        "license": "CC-BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
        "files": [
            "Zombie Growling.wav"
        ]
    },
    {
        "title": "6 Zombie Sounds",
        "author": "ChibiBagu",
        "url": "https://opengameart.org/content/6-zombie-sounds",
        "license": "CC-BY 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
        "files": [
            "Roar2.wav",
            "Roar3.wav"
        ]
    },
    {
        "title": "Bamboo stick swooshes",
        "author": "qubodup",
        "url": "https://opengameart.org/content/swish-bamboo-stick-weapon-swhoshes",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "swosh-01.flac",
            "swosh-02.flac",
            "swosh-03.flac",
            "swosh-04.flac"
        ]
    },
    {
        "title": "Impact Sounds",
        "author": "Kenney",
        "url": "https://kenney.nl/assets/impact-sounds",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "footstep_concrete_000.ogg",
            "footstep_concrete_001.ogg",
            "footstep_concrete_002.ogg",
            "footstep_concrete_003.ogg",
            "footstep_concrete_004.ogg",
            "footstep_grass_000.ogg",
            "footstep_grass_001.ogg",
            "footstep_grass_002.ogg",
            "footstep_grass_003.ogg",
            "footstep_wood_000.ogg",
            "footstep_wood_001.ogg",
            "footstep_wood_002.ogg",
            "footstep_wood_003.ogg",
            "impactBell_heavy_000.ogg",
            "impactBell_heavy_001.ogg",
            "impactBell_heavy_002.ogg",
            "impactBell_heavy_003.ogg",
            "impactGlass_light_000.ogg",
            "impactGlass_light_001.ogg",
            "impactGlass_light_002.ogg",
            "impactGlass_light_003.ogg",
            "impactGlass_medium_000.ogg",
            "impactGlass_medium_001.ogg",
            "impactMetal_heavy_000.ogg",
            "impactMetal_heavy_001.ogg",
            "impactMetal_heavy_002.ogg",
            "impactMetal_heavy_003.ogg",
            "impactMetal_light_000.ogg",
            "impactMetal_light_001.ogg",
            "impactMetal_light_002.ogg",
            "impactMetal_light_003.ogg",
            "impactMetal_medium_000.ogg",
            "impactMetal_medium_001.ogg",
            "impactMetal_medium_002.ogg",
            "impactMetal_medium_003.ogg",
            "impactPlate_light_000.ogg",
            "impactPlate_light_001.ogg",
            "impactPlate_light_002.ogg",
            "impactPlate_light_003.ogg",
            "impactPunch_medium_000.ogg",
            "impactPunch_medium_001.ogg",
            "impactPunch_medium_002.ogg",
            "impactPunch_medium_003.ogg",
            "impactSoft_heavy_000.ogg",
            "impactSoft_heavy_001.ogg",
            "impactSoft_heavy_002.ogg",
            "impactSoft_heavy_003.ogg",
            "impactSoft_medium_000.ogg",
            "impactSoft_medium_001.ogg",
            "impactSoft_medium_002.ogg",
            "impactSoft_medium_003.ogg",
            "impactTin_medium_000.ogg",
            "impactTin_medium_001.ogg",
            "impactTin_medium_002.ogg",
            "impactTin_medium_003.ogg",
            "impactWood_heavy_000.ogg",
            "impactWood_heavy_001.ogg",
            "impactWood_heavy_002.ogg",
            "impactWood_heavy_003.ogg"
        ]
    },
    {
        "title": "Fantozzi's Footsteps",
        "author": "Fantozzi",
        "url": "https://opengameart.org/content/fantozzis-footsteps-grasssand-stone",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "Fantozzi-SandL1.flac",
            "Fantozzi-SandL2.flac",
            "Fantozzi-SandR1.flac",
            "Fantozzi-SandR2.flac",
            "Fantozzi-StoneL1.flac",
            "Fantozzi-StoneL2.flac",
            "Fantozzi-StoneR1.flac",
            "Fantozzi-StoneR2.flac"
        ]
    },
    {
        "title": "Sirens and Alarm Noise",
        "author": "aquinn",
        "url": "https://opengameart.org/content/sirens-and-alarm-noise",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "siren_0.mp3"
        ]
    },
    {
        "title": "12 wet towel impacts",
        "author": "Iwan Gabovitch (qubodup)",
        "url": "https://opengameart.org/content/12-wet-towel-hittingfallingpunching-floor-sounds",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "wet_towel_on_floor-01.flac",
            "wet_towel_on_floor-02.flac",
            "wet_towel_on_floor-03.flac",
            "wet_towel_on_floor-04.flac"
        ]
    },
    {
        "title": "Dog barking mono",
        "author": "Brandon Morris",
        "url": "https://opengameart.org/content/dog-barking-mono",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "dog_barking_mono.wav"
        ]
    },
    {
        "title": "Zombie moans",
        "author": "Darsycho",
        "url": "https://opengameart.org/content/zombie-moans",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "darsycho__zombie-moans_0.ogg"
        ]
    },
    {
        "title": "Ambient Bird Sounds",
        "author": "isaiah658",
        "url": "https://opengameart.org/content/ambient-bird-sounds",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "birds-isaiah658_0.ogg"
        ]
    },
    {
        "title": "High traffic road sounds",
        "author": "IgnasD",
        "url": "https://opengameart.org/content/high-traffic-road-sounds",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "gatve Varniu_2.ogg"
        ]
    },
    {
        "title": "Crowd Shouting/Speaking Ambience",
        "author": "StarNinjas",
        "url": "https://opengameart.org/content/crowd-shoutingspeaking-ambience",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "crowd_shouting_0.ogg"
        ]
    },
    {
        "title": "Female high-pitched scream SFX",
        "author": "WuxiaScrub",
        "url": "https://opengameart.org/content/female-high-pitched-scream-sfx",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "screams_0.ogg"
        ]
    },
    {
        "title": "37 hits/punches",
        "author": "Independent.nu",
        "url": "https://opengameart.org/content/37-hitspunches",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "hit01.mp3.flac",
            "hit03.mp3.flac",
            "hit09.mp3.flac",
            "hit10.mp3.flac",
            "hit12.mp3.flac",
            "hit15.mp3.flac",
            "hit18.mp3.flac",
            "hit24.mp3.flac",
            "hit27.mp3.flac",
            "hit29.mp3.flac",
            "hit33.mp3.flac",
            "hit36.mp3.flac"
        ]
    },
    {
        "title": "80 CC0 creature SFX",
        "author": "rubberduck",
        "url": "https://opengameart.org/content/80-cc0-creature-sfx",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "eat_01.ogg",
            "eat_04.ogg",
            "scream_01.ogg",
            "scream_02.ogg"
        ]
    },
    {
        "title": "11 male human pain/death sounds",
        "author": "Michel Baradari",
        "url": "https://opengameart.org/content/11-male-human-paindeath-sounds",
        "license": "CC-BY 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
        "files": [
            "die1.wav",
            "die2.wav",
            "pain2.wav",
            "pain4.wav",
            "pain5.wav",
            "pain6.wav"
        ]
    },
    {
        "title": "Undead Moans",
        "author": "AntumDeluge",
        "url": "https://opengameart.org/content/undead-moans",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "undead-2.ogg"
        ]
    },
    {
        "title": "75 CC0 breaking / falling / hit SFX",
        "author": "rubberduck",
        "url": "https://opengameart.org/content/75-cc0-breaking-falling-hit-sfx",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "bfh1_glass_breaking_01.ogg",
            "bfh1_glass_breaking_02.ogg",
            "bfh1_glass_breaking_03.ogg",
            "bfh1_glass_breaking_04.ogg",
            "bfh1_glass_falling_01.ogg",
            "bfh1_glass_hit_01.ogg",
            "bfh1_glass_hit_02.ogg",
            "bfh1_metal_falling_01.ogg",
            "bfh1_metal_falling_02.ogg",
            "bfh1_metal_hit_01.ogg",
            "bfh1_metal_hit_02.ogg",
            "bfh1_metal_hit_03.ogg",
            "bfh1_metal_hit_04.ogg",
            "bfh1_rock_falling_01.ogg",
            "bfh1_rock_falling_02.ogg",
            "bfh1_rock_falling_03.ogg",
            "bfh1_rock_falling_04.ogg",
            "bfh1_wood_breaking_01.ogg",
            "bfh1_wood_breaking_02.ogg",
            "bfh1_wood_breaking_03.ogg",
            "bfh1_wood_breaking_04.ogg"
        ]
    },
    {
        "title": "100 CC0 SFX #2",
        "author": "rubberduck",
        "url": "https://opengameart.org/content/100-cc0-sfx-2",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "sfx100v2_door_01.ogg",
            "sfx100v2_door_02.ogg",
            "sfx100v2_door_03.ogg",
            "sfx100v2_door_04.ogg",
            "sfx100v2_footstep_wet_01.ogg",
            "sfx100v2_footstep_wet_02.ogg",
            "sfx100v2_footstep_wet_03.ogg",
            "sfx100v2_switch_01.ogg",
            "sfx100v2_switch_02.ogg"
        ]
    },
    {
        "title": "15 vocal male strain/hurt/pain/jump sounds",
        "author": "qubodup",
        "url": "https://opengameart.org/content/15-vocal-male-strainhurtpainjump-sounds",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "slightscream-02.flac",
            "slightscream-03.flac",
            "slightscream-04.flac",
            "slightscream-05.flac",
            "slightscream-06.flac",
            "slightscream-07.flac",
            "slightscream-08.flac",
            "slightscream-09.flac",
            "slightscream-11.flac",
            "slightscream-12.flac"
        ]
    },
    {
        "title": "Female RPG Voice Starter Pack (type 2, medium voice)",
        "author": "cicifyre",
        "url": "https://opengameart.org/content/female-rpg-voice-starter-pack",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "attack1.wav",
            "attack2.wav",
            "attack3.wav",
            "damaged1.wav",
            "damaged2.wav",
            "damaged3.wav",
            "jump1.wav",
            "jump2.wav",
            "jump3.wav"
        ]
    },
    {
        "title": "100 CC0 Metal and Wood SFX",
        "author": "rubberduck",
        "url": "https://opengameart.org/content/100-cc0-metal-and-wood-sfx",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "metal_close_01.ogg",
            "metal_hit_01.ogg",
            "metal_hit_02.ogg",
            "metal_hit_03.ogg",
            "metal_hit_04.ogg",
            "metal_open_01.ogg",
            "wood_close_01.ogg",
            "wood_close_02.ogg",
            "wood_cracking_01.ogg",
            "wood_cracking_02.ogg",
            "wood_cracking_03.ogg",
            "wood_cracking_04.ogg",
            "wood_hit_01.ogg",
            "wood_hit_02.ogg",
            "wood_hit_03.ogg",
            "wood_hit_04.ogg",
            "wood_slam_01.ogg",
            "wood_slam_02.ogg",
            "wood_slam_03.ogg",
            "wood_slam_04.ogg"
        ]
    },
    {
        "title": "Car Sound Effects Pack (Low Quality)",
        "author": "GGBotNet",
        "url": "https://opengameart.org/content/car-sound-effects-pack-low-quality",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "Car_Horn.ogg"
        ]
    },
    {
        "title": "Aggressive NPC sounds",
        "author": "mujtaba-io",
        "url": "https://opengameart.org/content/aggressive-npc-sounds-hey-i-will-kill-you",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "hey_aggressive_mujtaba.wav"
        ]
    },
    {
        "title": "Voice Effects Zombie-Skeleton-Monster Human Male",
        "author": "ArcadeParty",
        "url": "https://opengameart.org/content/zombie-skeleton-monster-voice-effects",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "zombieDeath1.wav",
            "zombieDeath2.wav",
            "zombieDeath3.wav",
            "zombieDeath4.wav",
            "zombieYell2.wav",
            "zombieYell4.wav",
            "zombieYell7.wav",
            "zombieYell9.wav"
        ]
    },
    {
        "title": "8 wet squish/slurp impacts",
        "author": "Independent.nu",
        "url": "https://opengameart.org/content/8-wet-squish-slurp-impacts",
        "license": "CC0",
        "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
        "files": [
            "impactsplat03.mp3.flac",
            "impactsplat07.mp3.flac"
        ]
    }
];
export const originalCredit: Credit = {
    "title": "Game code, 3D models, textures, UI art and synthesized cues",
    "author": "Minor Incident contributors",
    "url": "",
    "license": "MIT",
    "licenseUrl": "https://spdx.org/licenses/MIT.html",
    "detail": "Original work; synthesized system cues come from src/audio/synthesis.ts."
};
